# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created: Sun Dec 12 14:59:29 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 658)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/table_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.dbTab = QtGui.QWidget()
        self.dbTab.setObjectName("dbTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dbTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.dbTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFIO = QtGui.QLabel(self.groupBox)
        self.lblFIO.setObjectName("lblFIO")
        self.horizontalLayout.addWidget(self.lblFIO)
        self.lnEditFIO = QtGui.QLineEdit(self.groupBox)
        self.lnEditFIO.setObjectName("lnEditFIO")
        self.horizontalLayout.addWidget(self.lnEditFIO)
        self.lblGodRojd = QtGui.QLabel(self.groupBox)
        self.lblGodRojd.setObjectName("lblGodRojd")
        self.horizontalLayout.addWidget(self.lblGodRojd)
        self.lnEditGodOt = QtGui.QLineEdit(self.groupBox)
        self.lnEditGodOt.setObjectName("lnEditGodOt")
        self.horizontalLayout.addWidget(self.lnEditGodOt)
        self.lblDoGod = QtGui.QLabel(self.groupBox)
        self.lblDoGod.setObjectName("lblDoGod")
        self.horizontalLayout.addWidget(self.lblDoGod)
        self.lnEditGodDo = QtGui.QLineEdit(self.groupBox)
        self.lnEditGodDo.setObjectName("lnEditGodDo")
        self.horizontalLayout.addWidget(self.lnEditGodDo)
        self.lblSex = QtGui.QLabel(self.groupBox)
        self.lblSex.setObjectName("lblSex")
        self.horizontalLayout.addWidget(self.lblSex)
        self.cmbSex = QtGui.QComboBox(self.groupBox)
        self.cmbSex.setObjectName("cmbSex")
        self.cmbSex.addItem("")
        self.cmbSex.addItem("")
        self.cmbSex.addItem("")
        self.horizontalLayout.addWidget(self.cmbSex)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblDate = QtGui.QLabel(self.groupBox)
        self.lblDate.setObjectName("lblDate")
        self.horizontalLayout_2.addWidget(self.lblDate)
        self.dateBegin = QtGui.QDateEdit(self.groupBox)
        self.dateBegin.setObjectName("dateBegin")
        self.horizontalLayout_2.addWidget(self.dateBegin)
        self.lblDo = QtGui.QLabel(self.groupBox)
        self.lblDo.setObjectName("lblDo")
        self.horizontalLayout_2.addWidget(self.lblDo)
        self.dateEnd = QtGui.QDateEdit(self.groupBox)
        self.dateEnd.setObjectName("dateEnd")
        self.horizontalLayout_2.addWidget(self.dateEnd)
        self.lblOpis = QtGui.QLabel(self.groupBox)
        self.lblOpis.setObjectName("lblOpis")
        self.horizontalLayout_2.addWidget(self.lblOpis)
        self.lnEditOpis = QtGui.QLineEdit(self.groupBox)
        self.lnEditOpis.setObjectName("lnEditOpis")
        self.horizontalLayout_2.addWidget(self.lnEditOpis)
        self.btnClear = QtGui.QPushButton(self.groupBox)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_2.addWidget(self.btnClear)
        self.btnSearch = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_2.addWidget(self.btnSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.splitter = QtGui.QSplitter(self.dbTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.trePatients = QtGui.QTreeWidget(self.splitter)
        self.trePatients.setAlternatingRowColors(True)
        self.trePatients.setRootIsDecorated(False)
        self.trePatients.setUniformRowHeights(True)
        self.trePatients.setAllColumnsShowFocus(True)
        self.trePatients.setColumnCount(4)
        self.trePatients.setObjectName("trePatients")
        self.trePatients.header().setDefaultSectionSize(60)
        self.treProbes = QtGui.QTreeWidget(self.splitter)
        self.treProbes.setAlternatingRowColors(True)
        self.treProbes.setRootIsDecorated(False)
        self.treProbes.setUniformRowHeights(True)
        self.treProbes.setAllColumnsShowFocus(True)
        self.treProbes.setObjectName("treProbes")
        self.treProbes.header().setDefaultSectionSize(150)
        self.verticalLayout_3.addWidget(self.splitter)
        self.tabWidget.addTab(self.dbTab, "")
        self.viewTab = QtGui.QWidget()
        self.viewTab.setObjectName("viewTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.viewTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treExportProbes = QtGui.QTreeWidget(self.viewTab)
        self.treExportProbes.setAlternatingRowColors(True)
        self.treExportProbes.setRootIsDecorated(False)
        self.treExportProbes.setUniformRowHeights(True)
        self.treExportProbes.setAllColumnsShowFocus(True)
        self.treExportProbes.setObjectName("treExportProbes")
        self.treExportProbes.header().setDefaultSectionSize(80)
        self.horizontalLayout_3.addWidget(self.treExportProbes)
        self.graphicsView = QtGui.QGraphicsView(self.viewTab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.viewTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtGui.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarMain = QtGui.QToolBar(MainWindow)
        self.toolBarMain.setIconSize(QtCore.QSize(34, 34))
        self.toolBarMain.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBarMain.setObjectName("toolBarMain")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBarMain)
        self.actionDBOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/database_add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDBOpen.setIcon(icon1)
        self.actionDBOpen.setObjectName("actionDBOpen")
        self.actionDBClose = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/database_remove_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDBClose.setIcon(icon2)
        self.actionDBClose.setObjectName("actionDBClose")
        self.actionExport = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/box_upload_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon3)
        self.actionExport.setObjectName("actionExport")
        self.actMainToolBarVis = QtGui.QAction(MainWindow)
        self.actMainToolBarVis.setCheckable(True)
        self.actMainToolBarVis.setChecked(True)
        self.actMainToolBarVis.setObjectName("actMainToolBarVis")
        self.actHelpShow = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/warning_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actHelpShow.setIcon(icon4)
        self.actHelpShow.setObjectName("actHelpShow")
        self.actAboutShow = QtGui.QAction(MainWindow)
        self.actAboutShow.setIcon(icon)
        self.actAboutShow.setObjectName("actAboutShow")
        self.actionExit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/cross_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.actSelrctAll = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSelrctAll.setIcon(icon6)
        self.actSelrctAll.setObjectName("actSelrctAll")
        self.action = QtGui.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setCheckable(True)
        self.action_4.setChecked(True)
        self.action_4.setObjectName("action_4")
        self.action_1 = QtGui.QAction(MainWindow)
        self.action_1.setCheckable(True)
        self.action_1.setObjectName("action_1")
        self.menu.addAction(self.actionDBOpen)
        self.menu.addAction(self.actionDBClose)
        self.menu.addAction(self.actSelrctAll)
        self.menu.addAction(self.actionExport)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actMainToolBarVis)
        self.menu_2.addAction(self.action)
        self.menu_4.addAction(self.actHelpShow)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actAboutShow)
        self.menu_5.addAction(self.action_4)
        self.menu_5.addAction(self.action_1)
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_3.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBarMain.addAction(self.actionDBOpen)
        self.toolBarMain.addAction(self.actSelrctAll)
        self.toolBarMain.addAction(self.actionExport)
        self.toolBarMain.addAction(self.actionDBClose)
        self.toolBarMain.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Конвертер", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Фильтр", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFIO.setText(QtGui.QApplication.translate("MainWindow", "Ф.И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGodRojd.setText(QtGui.QApplication.translate("MainWindow", "Год рождения   От:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDoGod.setText(QtGui.QApplication.translate("MainWindow", "До:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSex.setText(QtGui.QApplication.translate("MainWindow", "Пол: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(0, QtGui.QApplication.translate("MainWindow", "муж.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(1, QtGui.QApplication.translate("MainWindow", "жен.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSex.setItemText(2, QtGui.QApplication.translate("MainWindow", "ж.б.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("MainWindow", "Дата съема   От:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDo.setText(QtGui.QApplication.translate("MainWindow", "До:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOpis.setText(QtGui.QApplication.translate("MainWindow", "Описание", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("MainWindow", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MainWindow", "Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.trePatients.setSortingEnabled(True)
        self.trePatients.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "№", None, QtGui.QApplication.UnicodeUTF8))
        self.trePatients.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Ф.И.О", None, QtGui.QApplication.UnicodeUTF8))
        self.trePatients.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Дата рождения", None, QtGui.QApplication.UnicodeUTF8))
        self.trePatients.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Пол", None, QtGui.QApplication.UnicodeUTF8))
        self.treProbes.setSortingEnabled(True)
        self.treProbes.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Дата съема", None, QtGui.QApplication.UnicodeUTF8))
        self.treProbes.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Описание", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dbTab), QtGui.QApplication.translate("MainWindow", "База данных", None, QtGui.QApplication.UnicodeUTF8))
        self.treExportProbes.setSortingEnabled(True)
        self.treExportProbes.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.treExportProbes.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Ф.И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.treExportProbes.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Дата съема", None, QtGui.QApplication.UnicodeUTF8))
        self.treExportProbes.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Описание", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewTab), QtGui.QApplication.translate("MainWindow", "Просмотр", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Вид", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "Справка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Инструменты", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_5.setTitle(QtGui.QApplication.translate("MainWindow", "Нормализация", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarMain.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDBOpen.setText(QtGui.QApplication.translate("MainWindow", "Открыть БД", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDBClose.setText(QtGui.QApplication.translate("MainWindow", "Закрыть БД", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Экспорт", None, QtGui.QApplication.UnicodeUTF8))
        self.actMainToolBarVis.setText(QtGui.QApplication.translate("MainWindow", "Главная", None, QtGui.QApplication.UnicodeUTF8))
        self.actHelpShow.setText(QtGui.QApplication.translate("MainWindow", "Содержание", None, QtGui.QApplication.UnicodeUTF8))
        self.actAboutShow.setText(QtGui.QApplication.translate("MainWindow", "О программе", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("MainWindow", "Закрыть программу", None, QtGui.QApplication.UnicodeUTF8))
        self.actSelrctAll.setText(QtGui.QApplication.translate("MainWindow", "Выбрать все", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "Инструменты", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("MainWindow", "Индекс напряжения", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "Без нормализации", None, QtGui.QApplication.UnicodeUTF8))
        self.action_1.setText(QtGui.QApplication.translate("MainWindow", "Нормализация 1", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
